#!/usr/bin/expect -f

#spawn ssh root@[lindex $argv 0] "grep processor /proc/cpuinfo | wc -l;grep MemTotal /proc/meminfo;df -h;lsb_release -a;yum list"
#spawn ssh -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no root@[lindex $argv 0] "service sshd restart"
#spawn scp -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no sshd_config root@[lindex $argv 0]:/etc/ssh/
spawn ssh -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no root@[lindex $argv 0] "echo 'admin	ALL=(ALL)	ALL'|tee -a /etc/sudoers; echo 'Defaults;admin !requiretty'|tee -a /etc/sudoers"
set timeout 10
expect {  
 "*yes/no" { send "yes\r"}  
 "*password:" { send "xxxxxx\r"}  
 "*password: " { send "xxxxxx\r"}  
}
